version: '3'

services:
  together.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  activity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  location.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  usergroup.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

